/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tcs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author Sanjith
 */
public class Bill extends javax.swing.JFrame {

    /**
     * Creates new form Bill
     */
    public Bill() {
        initComponents();
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        B2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        B3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        B4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        B5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        B6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        B7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        B8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        B9 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        B10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        B11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        B12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        B13 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        BB1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        BB2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        BB3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        BB4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        BB5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BB6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        BB7 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        BB8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        BB9 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        BB10 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        BB11 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1657, 10));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Billing ani.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 280, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel2.setText("SHOP ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 153, 90, 29));

        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 130, 29));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel3.setText("SHOP NAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 153, 95, 29));
        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 153, 140, 29));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel4.setText("LINE:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 153, 87, 29));

        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel1.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 130, 29));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 117, 10, 730));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel5.setText("TYPE:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, 84, 27));
        jPanel1.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, 27));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel6.setText("PHONE NO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 214, 95, 27));
        jPanel1.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 214, 140, 27));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel7.setText("PLACE:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 214, 87, 27));
        jPanel1.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 130, 27));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel8.setText("PRICE:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 271, 81, 26));
        jPanel1.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 130, 26));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel9.setText("BALANCE:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 271, 95, 26));
        jPanel1.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 271, 140, 26));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel10.setText("QUANTITY:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 275, 87, -1));
        jPanel1.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 130, 26));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 379, 820, 10));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/ok_1.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 338, 80, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 338, 90, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel11.setText("QUANTITY:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 441, 138, 39));
        jPanel1.add(B10, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 443, 125, 39));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel12.setText("PRICE:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 520, 138, 33));
        jPanel1.add(B11, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 522, 125, 33));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel13.setText("SUB-TOTAL:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 594, 138, 32));
        jPanel1.add(B12, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 594, 125, 32));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel14.setText("TOTAL:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 663, 138, 32));
        jPanel1.add(B13, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 663, 125, 32));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CLEAR");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 483, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/ok_1.png"))); // NOI18N
        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 566, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel15.setText("SHOP ID:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 139, 34));
        jPanel1.add(BB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 141, 35));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel16.setText("SHOP NAME:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 200, 127, 37));
        jPanel1.add(BB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 200, 140, 38));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel17.setText("LINE:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 100, 32));
        jPanel1.add(BB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 141, 37));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel18.setText("TYPE:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 270, 119, 34));
        jPanel1.add(BB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 270, 140, 35));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel19.setText("PHONE NO:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 120, 32));
        jPanel1.add(BB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, 141, 34));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel20.setText("DATE:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 340, 100, 34));
        jPanel1.add(BB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 340, 140, 34));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel21.setText("PLACE:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 139, 38));
        jPanel1.add(BB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, 141, 37));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1416, 430, 43, -1));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel23.setText("PRICE:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 410, 119, 35));

        jButton5.setText("D");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 340, 40, 30));
        jPanel1.add(BB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 410, 141, 35));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel24.setText("QUANTITY:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 120, -1));
        jPanel1.add(BB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 480, 141, 33));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel25.setText("SUB-TOTAL:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 490, 119, -1));
        jPanel1.add(BB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 480, 141, 33));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel26.setText("TOATL:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 580, 139, 38));
        jPanel1.add(BB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 580, 141, 38));

        jButton6.setText("SAVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 710, -1, -1));

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/Rectangle 1.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/smlogo2.png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/bill.jpg"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        
 String shopid=B1.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/TCSdb","root","");
                Statement stmt=(Statement)con.createStatement();
                ResultSet rs=stmt.executeQuery("select * from addSHOP where shopid like'"+shopid+"%'");
                if(rs.next()){
                    B1.setText(rs.getString(1));
                    B2.setText(rs.getString(2));
                    B3.setText(rs.getString(3));
                    B4.setText(rs.getString(4));
                    B5.setText(rs.getString(5));
                    B6.setText(rs.getString(6));
                    B7.setText(rs.getString(7));
                    B8.setText(rs.getString(8));
                    
                    
                }
                else{
                    
                    B2.setText("");
                    B3.setText("");
                    B4.setText("");
                    B5.setText("");
                    B6.setText("");
                    B7.setText("");
                    B8.setText("");
                    
                }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_B1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int prc=Integer.parseInt(B7.getText());
        int qty=Integer.parseInt(B9.getText());
        int bal=Integer.parseInt(B8.getText());
        int subtot=(qty*prc);
        int tot=(bal+subtot);
        if(B1.getText().length()<=0||B2.getText().length()<=0||B3.getText().length()<=0||B4.getText().length()<=0||B5.getText().length()<=0||B6.getText().length()<=0||B7.getText().length()<=0||B8.getText().length()<=0||B9.getText().length()<=0){
             JOptionPane.showMessageDialog(null, "Enter All The Feilds");
        }
        else{
            B10.setText(""+qty);
            B11.setText(""+prc);
            B12.setText(""+subtot);
            B13.setText(""+tot);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String shopid=B1.getText();
        String shopname=B2.getText();
        String line=B3.getText();
        String type=(String)B4.getText();
        String phno=B5.getText();
        String place=B6.getText();
        String amt =B7.getText();
        String bal=B8.getText();
        String qty=B9.getText();
        String subtot=B12.getText();
        String total=B13.getText();
        if(B10.getText().length()<=0||B11.getText().length()<=0||B12.getText().length()<=0||B13.getText().length()<=0){
            JOptionPane.showMessageDialog(null, " Feilds are Empty");
        }
        else{
             try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tcsdb","root","");
                Statement stmt=(Statement)con.createStatement();



                String UPDATE="UPDATE addshop SET bal='"+total+"' WHERE shopid='"+shopid+"' ";
                stmt.executeUpdate(UPDATE);
                
            }
            catch(Exception e){
                
            }
           
            BB1.setText(""+shopid);
            BB2.setText(""+shopname);
            BB3.setText(""+line);
            BB4.setText(""+type);
            BB5.setText(""+phno);
            BB7.setText(""+place);
            BB8.setText(""+amt);
            BB9.setText(""+qty);
            BB10.setText(""+subtot);
            BB11.setText(""+total);
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String shopid =BB1.getText();
        String shopname =BB2.getText();
        String line=BB3.getText();
        String type=BB4.getText();
        String phno=BB5.getText();
        String dt=BB6.getText();
        String place=BB7.getText();
        String amt=BB8.getText();
        String qty=BB9.getText();
        String subtot=BB10.getText();
        String total =BB11.getText();
          try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tcsdb","root", "");
                Statement stmt=con.createStatement();
                String INSERT="INSERT INTO bill VALUES('"+shopid+"','"+shopname+"','"+line+"','"+type+"','"+phno+"','"+dt+"','"+place+"','"+amt+"','"+qty+"','"+subtot+"','"+total+"')";
                stmt.executeUpdate(INSERT);
                JOptionPane.showMessageDialog(null, "ADDED");
            }
            catch(Exception e){
                System.out.println(e);
            }
             
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        SimpleDateFormat d=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        BB6.setText(d.format(date));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField B1;
    private javax.swing.JTextField B10;
    private javax.swing.JTextField B11;
    private javax.swing.JTextField B12;
    private javax.swing.JTextField B13;
    private javax.swing.JTextField B2;
    private javax.swing.JTextField B3;
    private javax.swing.JTextField B4;
    private javax.swing.JTextField B5;
    private javax.swing.JTextField B6;
    private javax.swing.JTextField B7;
    private javax.swing.JTextField B8;
    private javax.swing.JTextField B9;
    private javax.swing.JTextField BB1;
    private javax.swing.JTextField BB10;
    private javax.swing.JTextField BB11;
    private javax.swing.JTextField BB2;
    private javax.swing.JTextField BB3;
    private javax.swing.JTextField BB4;
    private javax.swing.JTextField BB5;
    private javax.swing.JTextField BB6;
    private javax.swing.JTextField BB7;
    private javax.swing.JTextField BB8;
    private javax.swing.JTextField BB9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
