/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tcs;

import java.awt.print.PrinterException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import java.util.Date;

/**
 *
 * @author Sanjith
 */
public class Invoice extends javax.swing.JFrame {

    // Define the method inside this class
    public static void displayShopDataByMonth(String shopid) {
        if (shopid == null || shopid.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Shop ID cannot be empty");
        
        }
    }
    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        t = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        d2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        d1 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        t1.setPreferredSize(new java.awt.Dimension(85, 22));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 159, 160, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEARCH");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1206, 152, 156, 47));

        tb1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SHOPID", "SHOPNAME", "LINE", "TYPE", "DATE", "QUANTITY", "PRICE", "SUB-TOTAL", "PAYMENT METHOD", "PAID AMOUNT", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 231, 1483, -1));

        t.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 690, 270, 60));

        b2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        b2.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 690, 330, 44));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("FROM:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 155, 88, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("SHOP ID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 153, 138, 44));

        d2.setBackground(new java.awt.Color(204, 0, 0));
        d2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel1.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 152, 183, 47));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setText("TO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 155, 62, 40));

        d1.setBackground(new java.awt.Color(255, 0, 0));
        d1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel1.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 152, 183, 47));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, 1514, 12));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/smlogo3.png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 160));

        jLabel2.setBackground(new java.awt.Color(51, 0, 0));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        jLabel2.setText("SUMMARY DETAILS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 360, 60));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 710, 170, 40));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/Rectangle 1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1462, 17, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String shopid = t1.getText().trim();

         if (d1.getDate() == null || d2.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select both From Date and To Date!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fromDate = sdf.format(d1.getDate());
        String toDate = sdf.format(d2.getDate());
         String url = "jdbc:mysql://localhost:3306/tcsdb";
        String user = "root";
        String password = "";

        String query = "SELECT b.shopid, b.shopname, b.line, b.type, b.dt AS date, " +
                       "COALESCE(b.qty, '-') AS quantity, COALESCE(b.amt, '-') AS price, " +
                       "COALESCE(b.subtot, '-') AS subtotal, '-' AS payment_method, " +
                       "'-' AS paid_amount, COALESCE(b.total, '-') AS total_balance " +
                       "FROM bill b WHERE b.shopid = ? AND b.dt BETWEEN ? AND ? " +
                       "UNION ALL " +
                       "SELECT c.shopid, c.shopname, c.line, c.type, c.dt AS date, " +
                       "'-' AS quantity, '-' AS price, '-' AS subtotal, c.paymentmd AS payment_method, " +
                       "c.amt AS paid_amount, c.totalbal AS total_balance " +
                       "FROM collection c WHERE c.shopid = ? AND c.dt BETWEEN ? AND ? " +
                       "ORDER BY date;";

        try (Connection conn = DriverManager.getConnection(url, user, password);
            java.sql.PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setString(1, shopid);
            stmt.setString(2, fromDate);
            stmt.setString(3, toDate);
            stmt.setString(4, shopid);
            stmt.setString(5, fromDate);
            stmt.setString(6, toDate);

            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tb1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getString("shopid"),
                        rs.getString("shopname"),
                        rs.getString("line"),
                        rs.getString("type"),
                        rs.getString("date"),
                        rs.getString("quantity"),
                        rs.getString("price"),
                        rs.getString("subtotal"),
                        rs.getString("payment_method"),
                        rs.getString("paid_amount"),
                        rs.getString("total_balance")
                });
            }
            fetchBalance();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database connection error!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    
    
    }//GEN-LAST:event_jButton1ActionPerformed
   private void fetchBalance() {
    String shopid = t1.getText().trim();
        String url = "jdbc:mysql://localhost:3306/tcsdb";
        String user = "root";
        String password = "";

        String query = "SELECT bal FROM addshop WHERE shopid = ?";

        try (Connection conn = DriverManager.getConnection(url, user, password);
             java.sql.PreparedStatement stmt = conn.prepareStatement(query)) {
            stmt.setString(1, shopid);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                b2.setText("Balance: " + rs.getString("bal"));
            } else {
                b2.setText("Balance: Not Found");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database connection error!", "Error", JOptionPane.ERROR_MESSAGE);
        }
   }
    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try {
        boolean complete = tb1.print(JTable.PrintMode.FIT_WIDTH, 
                                     new MessageFormat("Shop Report - " + t1.getText()), 
                                     new MessageFormat("Page {0}"));
        if (complete) {
            JOptionPane.showMessageDialog(this, "Printing Complete!", "Print", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Printing Cancelled!", "Print", JOptionPane.WARNING_MESSAGE);
        }
    } catch (PrinterException e) {
        JOptionPane.showMessageDialog(this, "Printing Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        String shopid = "l1"; // Example, replace with actual shop id input
        displayShopDataByMonth(shopid);//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b2;
    private com.toedter.calendar.JDateChooser d1;
    private com.toedter.calendar.JDateChooser d2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel t;
    private javax.swing.JTextField t1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
