/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tcs;

import tcs.SupplierBilling;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanjith
 */
public class SupllierCol extends javax.swing.JFrame {

    private String balance;

    /**
     * Creates new form SupllierCol
     */
    public SupllierCol() {
        initComponents();
        SimpleDateFormat d=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        S2.setText(d.format(date));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        S1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        S2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        S3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        S4 = new javax.swing.JTextField();
        S5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        S6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 22)); // NOI18N
        jLabel1.setText("BUYER NAME:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 149, 206, 45));

        S1.setToolTipText("");
        S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S1ActionPerformed(evt);
            }
        });
        jPanel1.add(S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 149, 225, 45));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 22)); // NOI18N
        jLabel2.setText("DATE:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 235, 206, 40));
        jPanel1.add(S2, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 237, 225, 42));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 22)); // NOI18N
        jLabel3.setText("BALANCE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 319, 206, 42));
        jPanel1.add(S3, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 322, 225, 42));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 22)); // NOI18N
        jLabel4.setText("PAYMENT:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 414, 206, 42));
        jPanel1.add(S4, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 417, 225, 42));
        jPanel1.add(S5, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 516, 225, 42));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 22)); // NOI18N
        jLabel5.setText("TOTAL:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 624, 206, 42));
        jPanel1.add(S6, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 624, 225, 42));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 22)); // NOI18N
        jLabel6.setText("PAY METHOD:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 522, 206, 42));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/calculate2.png"))); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1109, 517, 155, 42));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/save_1.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 730, 130, 40));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/Rectangle 1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/T   R   A   D   E   R   S SIDE2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/bill.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1569, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S1ActionPerformed
        String buyername=S1.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tcsdb","root","");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("SELECT * from supplier WHERE buyername like '"+buyername+"%'");
            if(rs.next()){
                S1.setText(rs.getString(1));
                S3.setText(rs.getString(2));
            }
            else{
                S3.setText("");
            }
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_S1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int balance=Integer.parseInt(S3.getText());
       int pay=Integer.parseInt(S4.getText());
       
       int tot=balance-pay;
       
       S6.setText(""+tot);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String buyername=S1.getText();
        String dt=S2.getText();
        String balance=S3.getText();
        String pay=S4.getText();
        String paymt=S5.getText();
        String tot=S6.getText();
        
         if(S1.getText().length()<=0||S2.getText().length()<=0||S3.getText().length()<=0||S4.getText().length()<=0||S5.getText().length()<=0||S6.getText().length()<=0){
           JOptionPane.showMessageDialog(null, "Enter All Fields");
       }
         else{
             try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
                 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tcsdb","root","");
                 Statement st=con.createStatement();
                 String INSERT="INSERT INTO supplier2 VALUES('"+buyername+"','"+dt+"','"+balance+"','"+pay+"','"+paymt+"','"+tot+"')";
                 String UPDATE="UPDATE supplier SET  balance='"+tot+"' where buyername='"+buyername+"'";
                 st.executeUpdate(INSERT);
                 st.executeUpdate(UPDATE);
                 JOptionPane.showMessageDialog(null, "SUCCESSFUL");
                 
                 
             }
             catch(Exception e){
                 System.out.println(e);
             }
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupllierCol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupllierCol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupllierCol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupllierCol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupllierCol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField S1;
    private javax.swing.JTextField S2;
    private javax.swing.JTextField S3;
    private javax.swing.JTextField S4;
    private javax.swing.JTextField S5;
    private javax.swing.JTextField S6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
