/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tcs;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
public class SupplierBilling extends javax.swing.JFrame {

    /**
     * Creates new form SupplierBilling
     */
    public SupplierBilling() {
        initComponents();
        SimpleDateFormat d=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        SB4.setText(d.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SB1 = new javax.swing.JTextField();
        SB2 = new javax.swing.JTextField();
        SB3 = new javax.swing.JTextField();
        SB5 = new javax.swing.JTextField();
        SB6 = new javax.swing.JTextField();
        SB7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SB4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder/Billing ani.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 18, 278, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel2.setText("BUYER NAME:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 156, 182, 37));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel3.setText("BRAND:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 175, 39));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel4.setText("DATE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 175, 37));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel5.setText("QUANTITY:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 175, 38));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel6.setText("PRICE:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 175, 35));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel7.setText("TOTAL :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, 175, 35));

        SB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SB1ActionPerformed(evt);
            }
        });
        jPanel1.add(SB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, 247, 37));
        jPanel1.add(SB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 247, 39));
        jPanel1.add(SB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 247, 37));
        jPanel1.add(SB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, 247, 38));
        jPanel1.add(SB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, 247, 35));
        jPanel1.add(SB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 690, 250, 35));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/calculate2.png"))); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 580, 148, 37));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/save_1.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 690, 150, 34));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/Rectangle 1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/T   R   A   D   E   R   S SIDE2.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel9.setAlignmentX(0.5F);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel11.setText("BALANCE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 175, 37));
        jPanel1.add(SB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 247, 37));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgimg/bill.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1640, 970));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int bal=Integer.parseInt(SB3.getText());
        int quantity=Integer.parseInt(SB5.getText());
        int price=Integer.parseInt(SB6.getText());
        int total=bal+(quantity*price);
        
        SB7.setText(""+total);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String buyername=SB1.getText();
       String brand=SB2.getText();
       String bal=SB3.getText();
       String dt=SB4.getText();
       String quantity=SB5.getText();
       String price=SB6.getText();
       String total=SB7.getText();
       
       if(SB1.getText().length()<=0||SB2.getText().length()<=0||SB3.getText().length()<=0||SB5.getText().length()<=0||SB6.getText().length()<=0||SB7.getText().length()<=0){
           JOptionPane.showMessageDialog(null, "Enter All Fields");
       }
       else{
           try{
               Class.forName("com.mysql.cj.jdbc.Driver");
               Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tcsdb", "root", "");
               Statement stmt=con.createStatement();
               String INSERT="INSERT INTO supplier1 VALUES('"+buyername+"','"+brand+"','"+bal+"','"+dt+"','"+quantity+"','"+price+"','"+total+"')";
               String UPDATE="UPDATE supplier SET balance='"+total+"' WHERE buyername='"+buyername+"'";
               stmt.executeUpdate(INSERT);
               stmt.executeUpdate(UPDATE);
               JOptionPane.showMessageDialog(null, "ADDED");
               
               SB1.setText("");
               SB2.setText("");
               SB3.setText("");
               SB5.setText("");
               SB6.setText("");
               SB7.setText("");
               
           }
           catch(Exception e){
               System.out.println(e);
               
           }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SB1ActionPerformed
        String buyername=SB1.getText();
        String balance=SB3.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tcsdb","root","");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM supplier WHERE buyername like '"+buyername+"%'");
            if(rs.next()){
                SB1.setText(rs.getString(1));
                SB3.setText(rs.getString(2));
            }
            else{
                SB3.setText("");
            }
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_SB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierBilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SB1;
    private javax.swing.JTextField SB2;
    private javax.swing.JTextField SB3;
    private javax.swing.JTextField SB4;
    private javax.swing.JTextField SB5;
    private javax.swing.JTextField SB6;
    private javax.swing.JTextField SB7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
